#!/usr/bin/env node
const FS = require('node:fs/promises')
const Path = require('node:path/posix')

const main = async () => {
  const packageJson = await FS.readFile('package.json', 'utf-8')
  const { name } = JSON.parse(packageJson)
  const dirname = Path.normalize(process.cwd()).split('/').at(-1)

  if (name !== dirname) {
    process.stderr.write(
      `  > Name does not match path: ${name} !== ${dirname}\n`
    )
    process.exitCode = 1
  }
}

main().catch((e) => {
  console.error(`package-name-matches-path failed: ${e}`)
})
