#!/usr/bin/env node

var config = require('./knexfile').development
var db = require('knex')(config)

var cmd = process.argv[2]
var note = process.argv[3]

switch (cmd) {
  case 'add':
    addTodo(note)
      .then(getAll)
      .then(listTodos)
      .catch(logError)
      .finally(closeDB)
    break

  case 'list':
    getAll()
      .then(listTodos)
      .catch(logError)
      .finally(closeDB)
    break

  default:
    console.log('No matched cases')
    closeDB()
    break
}

function listTodos (todos) {
  todos.forEach(function (todo) {
    console.info(todo.task)
  })
}

function logError (err) {
  console.error('Uh oh!', err)
}

function getAll () {
  return db('todos').select()
}

function addTodo (task) {
  return db('todos')
    .insert({
      task: task
    })
}

function closeDB () {
  db.destroy()
}
