// This code was largely generated by https://app.quicktype.io/ with a little bit of manual cleanup
export interface AmiiboCollection {
  amiibo: Amiibo[]
}

export interface Amiibo {
  amiiboSeries: string
  character: string
  gameSeries: string
  head: string
  image: string
  name: string
  release: Release
  tail: string
  type: Type
}

export interface Release {
  au: Date | null
  eu: Date | null
  jp: Date | null
  na: Date | null
}

export type Type = 'Card' | 'Figure' | 'Band'
